# Generated by Django 5.2.12 on 2026-03-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('location_details', models.TextField()),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='complaints/proofs/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_TALUK_REVIEW', 'Under Taluk Review'), ('UNDER_DISTRICT_REVIEW', 'Under District Review'), ('FORWARDED_TO_COMMISSIONER', 'Forwarded to Commissioner'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ASSIGNED_TO_AGENCY', 'Assigned to Agency'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=50)),
                ('assigned_agency', models.CharField(blank=True, choices=[('PUBLIC', 'Public User'), ('TALUK_OFFICER', 'Taluk Officer'), ('DISTRICT_OFFICER', 'District Officer'), ('COMMISSIONER', 'Commissioner'), ('AGENCY_INDANE', 'Agency - Indane'), ('AGENCY_HP', 'Agency - HP Gas'), ('AGENCY_BHARAT', 'Agency - Bharat Gas')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_TALUK_REVIEW', 'Under Taluk Review'), ('UNDER_DISTRICT_REVIEW', 'Under District Review'), ('FORWARDED_TO_COMMISSIONER', 'Forwarded to Commissioner'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ASSIGNED_TO_AGENCY', 'Assigned to Agency'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='complaints/resolution_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Taluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
