# Generated by Django 5.2.12 on 2026-03-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_agencystock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencystock',
            old_name='notes',
            new_name='remarks',
        ),
        migrations.AddField(
            model_name='agencystock',
            name='days_cover',
            field=models.FloatField(default=0.0, help_text='Number of days supply'),
        ),
        migrations.AddField(
            model_name='agencystock',
            name='in_transit_stock',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='agencystock',
            name='installed_capacity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='agencystock',
            name='location_name',
            field=models.CharField(default='General Plant', help_text='e.g., Cochin LPG Bottling Plant', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencystock',
            name='opening_stock_domestic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='agencystock',
            name='opening_stock_non_domestic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='agencystock',
            name='opening_stock_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='agencystock',
            name='operational_capacity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='agencystock',
            name='prev_day_dispatch',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='agencystock',
            name='product',
            field=models.CharField(choices=[('LPG', 'LPG'), ('PROPANE', 'Propane'), ('BUTANE', 'Butane')], default='LPG', max_length=20),
        ),
        migrations.AddField(
            model_name='agencystock',
            name='receipts_prev_day',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='agencystock',
            name='agency_type',
            field=models.CharField(choices=[('INDANE', 'IOCL – Indian Oil Corporation Limited'), ('HP', 'HPCL – Hindustan Petroleum Corporation Limited'), ('BHARAT', 'BPCL – Bharat Petroleum Corporation Limited')], max_length=10),
        ),
    ]
