# Generated by Django 5.2.12 on 2026-03-14 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_rename_notes_agencystock_remarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='consumer_agency_type',
            field=models.CharField(blank=True, choices=[('INDANE', 'Indane'), ('BHARAT', 'Bharat'), ('HP', 'HP'), ('NONE', 'None')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='consumer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='consumer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
