# Generated by Django 5.2.12 on 2026-03-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_consumer_agency_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='cylinder_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='complaint',
            name='cylinder_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
