# Generated by Django 5.2.12 on 2026-03-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_cylinder_count_complaint_cylinder_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='center_type',
            field=models.CharField(choices=[('RETAILER', 'Retailer'), ('DISTRIBUTOR', 'Distributor'), ('REFINERY', 'Refinery'), ('OTHERS', 'Others')], default='OTHERS', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='consumer_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sector',
            field=models.CharField(choices=[('DOMESTIC', 'Domestic'), ('COMMERCIAL', 'Commercial')], default='DOMESTIC', max_length=20),
        ),
    ]
