# Generated by Django 5.2.12 on 2026-03-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_complaint_center_type_complaint_consumer_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='center_type',
            field=models.CharField(choices=[('HOSPITAL', 'Hospitals'), ('EDUCATION', 'Educational institutes'), ('PHARMA', 'Pharmaceutical Industry'), ('SEED', 'Seed Processing industry'), ('FISHERIES', 'Fisheries Industry'), ('TRANSPORT_CANTEEN', 'Airline/ Railway Canteens'), ('RESTAURANT', 'Restaurant/Dhaba'), ('HOTEL', 'Hotel Industry'), ('CORPORATE_CANTEEN', 'Corporate Canteen'), ('INDUSTRIAL_CANTEEN', 'Industrial Canteens'), ('GUEST_HOUSE', 'Corporate Guest House'), ('FOOD_DIARY', 'Food Processing/Diary Industry'), ('STEEL', 'Steel Industry'), ('POWER', 'Power Industry'), ('AUTOMOBILE', 'Automobile Industry'), ('CERAMIC_GLASS', 'Ceramic/ Glass Industry'), ('TEXTILE_DYE', 'Textile/Dye Industry'), ('FOUNDRY', 'Foundry Forge Industry'), ('CHEMICAL_PLASTIC', 'Chemical / Plastics Industry'), ('OTHERS', 'Others / Case-to-case basis')], default='OTHERS', max_length=50),
        ),
    ]
