# Generated by Django 6.0.3 on 2026-03-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency_type',
            field=models.CharField(choices=[('INDANE', 'Indane'), ('BHARAT', 'Bharat'), ('HP', 'HP'), ('NONE', 'None')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
