# Generated by Django 6.0.3 on 2026-03-13 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_notification'),
        ('users', '0002_user_agency_type_user_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.district'),
        ),
        migrations.AddField(
            model_name='user',
            name='taluk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.taluk'),
        ),
    ]
