# Generated by Django 5.2.12 on 2026-03-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_district_user_taluk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consumer_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
